language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t edraobdu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true edraobdu/docker-react npm run test